openapi: 3.0.3
info:
  title: User Service API
  version: 1.0.0
servers:
- url: /
paths:
  /v1/users/{id}:
    get:
      operationId: getUser
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
          description: Successful response
      summary: Get user by ID
      x-accepts:
      - application/json
components:
  schemas:
    UserDto:
      example:
        name: name
        id: 0
        email: email
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
      type: object

