server:
  port: 8086

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


  server:
      port: 8080

      springdoc:
        api-docs:
          path: /v3/api-docs